export const DIRECCIONES = [
  // GUATEMALA
  { codigo: '0101', nombreCompleto: 'Guatemala, Guatemala' },
  { codigo: '0102', nombreCompleto: 'Guatemala, Santa Catarina Pinula' },
  { codigo: '0103', nombreCompleto: 'Guatemala, San José Pinula' },
  { codigo: '0104', nombreCompleto: 'Guatemala, San José del Golfo' },
  { codigo: '0105', nombreCompleto: 'Guatemala, Palencia' },
  { codigo: '0106', nombreCompleto: 'Guatemala, Chinautla' },
  { codigo: '0107', nombreCompleto: 'Guatemala, San Pedro Ayampuc' },
  { codigo: '0108', nombreCompleto: 'Guatemala, Mixco' },
  { codigo: '0109', nombreCompleto: 'Guatemala, San Pedro Sacatepéquez' },
  { codigo: '0110', nombreCompleto: 'Guatemala, San Juan Sacatepéquez' },
  { codigo: '0111', nombreCompleto: 'Guatemala, San Raymundo' },
  { codigo: '0112', nombreCompleto: 'Guatemala, Chuarrancho' },
  { codigo: '0113', nombreCompleto: 'Guatemala, Fraijanes' },
  { codigo: '0114', nombreCompleto: 'Guatemala, Amatitlán' },
  { codigo: '0115', nombreCompleto: 'Guatemala, Villa Nueva' },
  { codigo: '0116', nombreCompleto: 'Guatemala, Villa Canales' },
  { codigo: '0117', nombreCompleto: 'Guatemala, San Miguel Petapa' },

  // EL PROGRESO
  { codigo: '0201', nombreCompleto: 'El Progreso, Guastatoya' },
  { codigo: '0202', nombreCompleto: 'El Progreso, Morazán' },
  { codigo: '0203', nombreCompleto: 'El Progreso, San Agustín Acasaguastlán' },
  { codigo: '0204', nombreCompleto: 'El Progreso, San Cristóbal Acasaguastlán' },
  { codigo: '0205', nombreCompleto: 'El Progreso, El Jícaro' },
  { codigo: '0206', nombreCompleto: 'El Progreso, Sansare' },
  { codigo: '0207', nombreCompleto: 'El Progreso, Sanarate' },
  { codigo: '0208', nombreCompleto: 'El Progreso, San Antonio La Paz' },

  // SACATEPÉQUEZ
  { codigo: '0301', nombreCompleto: 'Sacatepéquez, Antigua Guatemala' },
  { codigo: '0302', nombreCompleto: 'Sacatepéquez, Jocotenango' },
  { codigo: '0303', nombreCompleto: 'Sacatepéquez, Pastores' },
  { codigo: '0304', nombreCompleto: 'Sacatepéquez, Sumpango' },
  { codigo: '0305', nombreCompleto: 'Sacatepéquez, Santo Domingo Xenacoj' },
  { codigo: '0306', nombreCompleto: 'Sacatepéquez, Santiago Sacatepéquez' },
  { codigo: '0307', nombreCompleto: 'Sacatepéquez, San Bartolomé Milpas Altas' },
  { codigo: '0308', nombreCompleto: 'Sacatepéquez, San Lucas Sacatepéquez' },
  { codigo: '0309', nombreCompleto: 'Sacatepéquez, Santa Lucía Milpas Altas' },
  { codigo: '0310', nombreCompleto: 'Sacatepéquez, Magdalena Milpas Altas' },
  { codigo: '0311', nombreCompleto: 'Sacatepéquez, Santa María de Jesús' },
  { codigo: '0312', nombreCompleto: 'Sacatepéquez, Ciudad Vieja' },
  { codigo: '0313', nombreCompleto: 'Sacatepéquez, San Miguel Dueñas' },
  { codigo: '0314', nombreCompleto: 'Sacatepéquez, Alotenango' },
  { codigo: '0315', nombreCompleto: 'Sacatepéquez, San Antonio Aguas Calientes' },
  { codigo: '0316', nombreCompleto: 'Sacatepéquez, Santa Catarina Barahona' },

  // CHIMALTENANGO
  { codigo: '0401', nombreCompleto: 'Chimaltenango, Chimaltenango' },
  { codigo: '0402', nombreCompleto: 'Chimaltenango, San José Poaquil' },
  { codigo: '0403', nombreCompleto: 'Chimaltenango, San Martín Jilotepeque' },
  { codigo: '0404', nombreCompleto: 'Chimaltenango, San Juan Comalapa' },
  { codigo: '0405', nombreCompleto: 'Chimaltenango, Santa Apolonia' },
  { codigo: '0406', nombreCompleto: 'Chimaltenango, Tecpán Guatemala' },
  { codigo: '0407', nombreCompleto: 'Chimaltenango, Patzún' },
  { codigo: '0408', nombreCompleto: 'Chimaltenango, San Miguel Pochuta' },
  { codigo: '0409', nombreCompleto: 'Chimaltenango, Patzicía' },
  { codigo: '0410', nombreCompleto: 'Chimaltenango, Santa Cruz Balanyá' },
  { codigo: '0411', nombreCompleto: 'Chimaltenango, Acatenango' },
  { codigo: '0412', nombreCompleto: 'Chimaltenango, San Pedro Yepocapa' },
  { codigo: '0413', nombreCompleto: 'Chimaltenango, San Andrés Itzapa' },
  { codigo: '0414', nombreCompleto: 'Chimaltenango, Parramos' },
  { codigo: '0415', nombreCompleto: 'Chimaltenango, Zaragoza' },
  { codigo: '0416', nombreCompleto: 'Chimaltenango, El Tejar' },

    // Escuintla
    { codigo: '0501', nombreCompleto: 'Escuintla, Escuintla' },
    { codigo: '0502', nombreCompleto: 'Escuintla, Santa Lucía Cotzumalguapa' },
    { codigo: '0503', nombreCompleto: 'Escuintla, La Democracia' },
    { codigo: '0504', nombreCompleto: 'Escuintla, Siquinalá' },
    { codigo: '0505', nombreCompleto: 'Escuintla, Masagua' },
    { codigo: '0506', nombreCompleto: 'Escuintla, Tiquisate' },
    { codigo: '0507', nombreCompleto: 'Escuintla, La Gomera' },
    { codigo: '0508', nombreCompleto: 'Escuintla, Guanagazapa' },
    { codigo: '0509', nombreCompleto: 'Escuintla, San José' },
    { codigo: '0510', nombreCompleto: 'Escuintla, Iztapa' },
    { codigo: '0511', nombreCompleto: 'Escuintla, Palín' },
    { codigo: '0512', nombreCompleto: 'Escuintla, San Vicente Pacaya' },
    { codigo: '0513', nombreCompleto: 'Escuintla, Nueva Concepción' },

    // Santa Rosa
    { codigo: '0601', nombreCompleto: 'Santa Rosa, Cuilapa' },
    { codigo: '0602', nombreCompleto: 'Santa Rosa, Barberena' },
    { codigo: '0603', nombreCompleto: 'Santa Rosa, Santa Rosa de Lima' },
    { codigo: '0604', nombreCompleto: 'Santa Rosa, Casillas' },
    { codigo: '0605', nombreCompleto: 'Santa Rosa, San Rafael Las Flores' },
    { codigo: '0606', nombreCompleto: 'Santa Rosa, Oratorio' },
    { codigo: '0607', nombreCompleto: 'Santa Rosa, San Juan Tecuaco' },
    { codigo: '0608', nombreCompleto: 'Santa Rosa, Chiquimulilla' },
    { codigo: '0609', nombreCompleto: 'Santa Rosa, Taxisco' },
    { codigo: '0610', nombreCompleto: 'Santa Rosa, Santa María Ixhuatán' },
    { codigo: '0611', nombreCompleto: 'Santa Rosa, Guazacapán' },
    { codigo: '0612', nombreCompleto: 'Santa Rosa, Santa Cruz Naranjo' },
    { codigo: '0613', nombreCompleto: 'Santa Rosa, Pueblo Nuevo Viñas' },
    { codigo: '0614', nombreCompleto: 'Santa Rosa, Nueva Santa Rosa' },

    // Sololá
    { codigo: '0701', nombreCompleto: 'Sololá, Sololá' },
    { codigo: '0702', nombreCompleto: 'Sololá, San José Chacayá' },
    { codigo: '0703', nombreCompleto: 'Sololá, Santa María Visitación' },
    { codigo: '0704', nombreCompleto: 'Sololá, Santa Lucía Utatlán' },
    { codigo: '0705', nombreCompleto: 'Sololá, Nahualá' },
    { codigo: '0706', nombreCompleto: 'Sololá, Santa Catarina Ixtahuacán' },
    { codigo: '0707', nombreCompleto: 'Sololá, Santa Clara La Laguna' },
    { codigo: '0708', nombreCompleto: 'Sololá, Concepción' },
    { codigo: '0709', nombreCompleto: 'Sololá, San Andrés Semetabaj' },
    { codigo: '0710', nombreCompleto: 'Sololá, Panajachel' },
    { codigo: '0711', nombreCompleto: 'Sololá, Santa Catarina Palopó' },
    { codigo: '0712', nombreCompleto: 'Sololá, San Antonio Palopó' },
    { codigo: '0713', nombreCompleto: 'Sololá, San Lucas Tolimán' },
    { codigo: '0714', nombreCompleto: 'Sololá, Santa Cruz La Laguna' },
    { codigo: '0715', nombreCompleto: 'Sololá, San Pablo La Laguna' },
    { codigo: '0716', nombreCompleto: 'Sololá, San Marcos La Laguna' },
    { codigo: '0717', nombreCompleto: 'Sololá, San Juan La Laguna' },
    { codigo: '0718', nombreCompleto: 'Sololá, San Pedro La Laguna' },
    { codigo: '0719', nombreCompleto: 'Sololá, Santiago Atitlán' },

    // Totonicapán
    { codigo: '0801', nombreCompleto: 'Totonicapán, Totonicapán' },
    { codigo: '0802', nombreCompleto: 'Totonicapán, San Cristóbal Totonicapán' },
    { codigo: '0803', nombreCompleto: 'Totonicapán, San Francisco El Alto' },
    { codigo: '0804', nombreCompleto: 'Totonicapán, San Andrés Xecul' },
    { codigo: '0805', nombreCompleto: 'Totonicapán, Momostenango' },
    { codigo: '0806', nombreCompleto: 'Totonicapán, Santa María Chiquimula' },
    { codigo: '0807', nombreCompleto: 'Totonicapán, Santa Lucía La Reforma' },
    { codigo: '0808', nombreCompleto: 'Totonicapán, San Bartolo Aguas Calientes' },

     // Quetzaltenango
  { codigo: '0901', nombreCompleto: 'Quetzaltenango, Quetzaltenango' },
  { codigo: '0902', nombreCompleto: 'Quetzaltenango, Salcajá' },
  { codigo: '0903', nombreCompleto: 'Quetzaltenango, Olintepeque' },
  { codigo: '0904', nombreCompleto: 'Quetzaltenango, San Carlos Sija' },
  { codigo: '0905', nombreCompleto: 'Quetzaltenango, Sibilia' },
  { codigo: '0906', nombreCompleto: 'Quetzaltenango, Cabricán' },
  { codigo: '0907', nombreCompleto: 'Quetzaltenango, Cajolá' },
  { codigo: '0908', nombreCompleto: 'Quetzaltenango, San Miguel Siguilá' },
  { codigo: '0909', nombreCompleto: 'Quetzaltenango, San Juan Ostuncalco' },
  { codigo: '0910', nombreCompleto: 'Quetzaltenango, San Mateo' },
  { codigo: '0911', nombreCompleto: 'Quetzaltenango, Concepción Chiquirichapa' },
  { codigo: '0912', nombreCompleto: 'Quetzaltenango, San Martín Sacatepéquez' },
  { codigo: '0913', nombreCompleto: 'Quetzaltenango, Almolonga' },
  { codigo: '0914', nombreCompleto: 'Quetzaltenango, Cantel' },
  { codigo: '0915', nombreCompleto: 'Quetzaltenango, Huitán' },
  { codigo: '0916', nombreCompleto: 'Quetzaltenango, Zunil' },
  { codigo: '0917', nombreCompleto: 'Quetzaltenango, Colomba Costa Cuca' },
  { codigo: '0918', nombreCompleto: 'Quetzaltenango, San Francisco La Unión' },
  { codigo: '0919', nombreCompleto: 'Quetzaltenango, El Palmar' },
  { codigo: '0920', nombreCompleto: 'Quetzaltenango, Coatepeque' },
  { codigo: '0921', nombreCompleto: 'Quetzaltenango, Génova Costa Cuca' },
  { codigo: '0922', nombreCompleto: 'Quetzaltenango, Flores Costa Cuca' },
  { codigo: '0923', nombreCompleto: 'Quetzaltenango, La Esperanza' },
  { codigo: '0924', nombreCompleto: 'Quetzaltenango, Palestina de los Altos' },

  // Suchitepéquez
  { codigo: '1001', nombreCompleto: 'Suchitepéquez, Mazatenango' },
  { codigo: '1002', nombreCompleto: 'Suchitepéquez, Cuyotenango' },
  { codigo: '1003', nombreCompleto: 'Suchitepéquez, San Francisco Zapotitlán' },
  { codigo: '1004', nombreCompleto: 'Suchitepéquez, San Bernardino' },
  { codigo: '1005', nombreCompleto: 'Suchitepéquez, San José El Ídolo' },
  { codigo: '1006', nombreCompleto: 'Suchitepéquez, Santo Domingo Suchitepéquez' },
  { codigo: '1007', nombreCompleto: 'Suchitepéquez, San Lorenzo' },
  { codigo: '1008', nombreCompleto: 'Suchitepéquez, Samayac' },
  { codigo: '1009', nombreCompleto: 'Suchitepéquez, San Pablo Jocopilas' },
  { codigo: '1010', nombreCompleto: 'Suchitepéquez, San Antonio Suchitepéquez' },
  { codigo: '1011', nombreCompleto: 'Suchitepéquez, San Miguel Panán' },
  { codigo: '1012', nombreCompleto: 'Suchitepéquez, San Gabriel' },
  { codigo: '1013', nombreCompleto: 'Suchitepéquez, Chicacao' },
  { codigo: '1014', nombreCompleto: 'Suchitepéquez, Patulul' },
  { codigo: '1015', nombreCompleto: 'Suchitepéquez, Santa Bárbara' },
  { codigo: '1016', nombreCompleto: 'Suchitepéquez, San Juan Bautista' },
  { codigo: '1017', nombreCompleto: 'Suchitepéquez, Santo Tomás La Unión' },
  { codigo: '1018', nombreCompleto: 'Suchitepéquez, Zunilito' },
  { codigo: '1019', nombreCompleto: 'Suchitepéquez, Pueblo Nuevo' },
  { codigo: '1020', nombreCompleto: 'Suchitepéquez, Río Bravo' },

  // Retalhuleu
  { codigo: '1101', nombreCompleto: 'Retalhuleu, Retalhuleu' },
  { codigo: '1102', nombreCompleto: 'Retalhuleu, San Sebastián' },
  { codigo: '1103', nombreCompleto: 'Retalhuleu, Santa Cruz Muluá' },
  { codigo: '1104', nombreCompleto: 'Retalhuleu, San Martín Zapotitlán' },
  { codigo: '1105', nombreCompleto: 'Retalhuleu, San Felipe' },
  { codigo: '1106', nombreCompleto: 'Retalhuleu, San Andrés Villa Seca' },
  { codigo: '1107', nombreCompleto: 'Retalhuleu, Champerico' },
  { codigo: '1108', nombreCompleto: 'Retalhuleu, Nuevo San Carlos' },
  { codigo: '1109', nombreCompleto: 'Retalhuleu, El Asintal' },

  // San Marcos
  { codigo: '1201', nombreCompleto: 'San Marcos, San Marcos' },
  { codigo: '1202', nombreCompleto: 'San Marcos, San Pedro Sacatepéquez' },
  { codigo: '1203', nombreCompleto: 'San Marcos, San Antonio Sacatepéquez' },
  { codigo: '1204', nombreCompleto: 'San Marcos, Comitancillo' },
  { codigo: '1205', nombreCompleto: 'San Marcos, San Miguel Ixtahuacán' },
  { codigo: '1206', nombreCompleto: 'San Marcos, Concepción Tutuapa' },
  { codigo: '1207', nombreCompleto: 'San Marcos, Tacaná' },
  { codigo: '1208', nombreCompleto: 'San Marcos, Sibinal' },
  { codigo: '1209', nombreCompleto: 'San Marcos, Tajumulco' },
  { codigo: '1210', nombreCompleto: 'San Marcos, Tejutla' },
  { codigo: '1211', nombreCompleto: 'San Marcos, San Rafael Pie de la Cuesta' },
  { codigo: '1212', nombreCompleto: 'San Marcos, Nuevo Progreso' },
  { codigo: '1213', nombreCompleto: 'San Marcos, El Tumbador' },
  { codigo: '1214', nombreCompleto: 'San Marcos, San José El Rodeo' },
  { codigo: '1215', nombreCompleto: 'San Marcos, Malacatán' },
  { codigo: '1216', nombreCompleto: 'San Marcos, Catarina' },
  { codigo: '1217', nombreCompleto: 'San Marcos, Ayutla (Tecún Umán)' },
  { codigo: '1218', nombreCompleto: 'San Marcos, Ocós' },
  { codigo: '1219', nombreCompleto: 'San Marcos, San Pablo' },
  { codigo: '1220', nombreCompleto: 'San Marcos, El Quetzal' },
  { codigo: '1221', nombreCompleto: 'San Marcos, La Reforma' },
  { codigo: '1222', nombreCompleto: 'San Marcos, Pajapita' },
  { codigo: '1223', nombreCompleto: 'San Marcos, Ixchiguán' },
  { codigo: '1224', nombreCompleto: 'San Marcos, San José Ojetenam' },
  { codigo: '1225', nombreCompleto: 'San Marcos, San Cristóbal Cucho' },
  { codigo: '1226', nombreCompleto: 'San Marcos, Sipacapa' },
  { codigo: '1227', nombreCompleto: 'San Marcos, Esquipulas Palo Gordo' },
  { codigo: '1228', nombreCompleto: 'San Marcos, Río Blanco' },
  { codigo: '1229', nombreCompleto: 'San Marcos, San Lorenzo' },

  // Huehuetenango
  { codigo: '1301', nombreCompleto: 'Huehuetenango, Huehuetenango' },
  { codigo: '1302', nombreCompleto: 'Huehuetenango, Chiantla' },
  { codigo: '1303', nombreCompleto: 'Huehuetenango, Malacatancito' },
  { codigo: '1304', nombreCompleto: 'Huehuetenango, Cuilco' },
  { codigo: '1305', nombreCompleto: 'Huehuetenango, Nentón' },
  { codigo: '1306', nombreCompleto: 'Huehuetenango, San Pedro Necta' },
  { codigo: '1307', nombreCompleto: 'Huehuetenango, Jacaltenango' },
  { codigo: '1308', nombreCompleto: 'Huehuetenango, San Pedro Soloma' },
  { codigo: '1309', nombreCompleto: 'Huehuetenango, San Ildefonso Ixtahuacán' },
  { codigo: '1310', nombreCompleto: 'Huehuetenango, Santa Bárbara' },
  { codigo: '1311', nombreCompleto: 'Huehuetenango, La Libertad' },
  { codigo: '1312', nombreCompleto: 'Huehuetenango, La Democracia' },
  { codigo: '1313', nombreCompleto: 'Huehuetenango, San Miguel Acatán' },
  { codigo: '1314', nombreCompleto: 'Huehuetenango, San Rafael La Independencia' },
  { codigo: '1315', nombreCompleto: 'Huehuetenango, Todos Santos Cuchumatán' },
  { codigo: '1316', nombreCompleto: 'Huehuetenango, San Juan Atitán' },
  { codigo: '1317', nombreCompleto: 'Huehuetenango, Santa Eulalia' },
  { codigo: '1318', nombreCompleto: 'Huehuetenango, San Mateo Ixtatán' },
  { codigo: '1319', nombreCompleto: 'Huehuetenango, Colotenango' },
  { codigo: '1320', nombreCompleto: 'Huehuetenango, San Sebastián Huehuetenango' },
  { codigo: '1321', nombreCompleto: 'Huehuetenango, Tectitán' },
  { codigo: '1322', nombreCompleto: 'Huehuetenango, Concepción Huista' },
  { codigo: '1323', nombreCompleto: 'Huehuetenango, San Juan Ixcoy' },
  { codigo: '1324', nombreCompleto: 'Huehuetenango, San Antonio Huista' },
  { codigo: '1325', nombreCompleto: 'Huehuetenango, San Sebastián Coatán' },
  { codigo: '1326', nombreCompleto: 'Huehuetenango, Santa Cruz Barillas' },
  { codigo: '1327', nombreCompleto: 'Huehuetenango, Aguacatán' },
  { codigo: '1328', nombreCompleto: 'Huehuetenango, San Rafael Petzal' },
  { codigo: '1329', nombreCompleto: 'Huehuetenango, San Gaspar Ixchil' },
  { codigo: '1330', nombreCompleto: 'Huehuetenango, Santiago Chimaltenango' },
  { codigo: '1331', nombreCompleto: 'Huehuetenango, Santa Ana Huista' },
  { codigo: '1332', nombreCompleto: 'Huehuetenango, Unión Cantinil' },

  // Quiché
  { codigo: '1401', nombreCompleto: 'Quiché, Santa Cruz del Quiché' },
  { codigo: '1402', nombreCompleto: 'Quiché, Chiché' },
  { codigo: '1403', nombreCompleto: 'Quiché, Chinique' },
  { codigo: '1404', nombreCompleto: 'Quiché, Zacualpa' },
  { codigo: '1405', nombreCompleto: 'Quiché, Chajul' },
  { codigo: '1406', nombreCompleto: 'Quiché, Santo Tomás Chichicastenango' },
  { codigo: '1407', nombreCompleto: 'Quiché, Patzité' },
  { codigo: '1408', nombreCompleto: 'Quiché, San Antonio Ilotenango' },
  { codigo: '1409', nombreCompleto: 'Quiché, San Pedro Jocopilas' },
  { codigo: '1410', nombreCompleto: 'Quiché, Cunén' },
  { codigo: '1411', nombreCompleto: 'Quiché, San Juan Cotzal' },
  { codigo: '1412', nombreCompleto: 'Quiché, Joyabaj' },
  { codigo: '1413', nombreCompleto: 'Quiché, Nebaj' },
  { codigo: '1414', nombreCompleto: 'Quiché, San Andrés Sajcabajá' },
  { codigo: '1415', nombreCompleto: 'Quiché, San Miguel Uspantán' },
  { codigo: '1416', nombreCompleto: 'Quiché, Sacapulas' },
  { codigo: '1417', nombreCompleto: 'Quiché, San Bartolomé Jocotenango' },
  { codigo: '1418', nombreCompleto: 'Quiché, Canillá' },
  { codigo: '1419', nombreCompleto: 'Quiché, Chicamán' },
  { codigo: '1420', nombreCompleto: 'Quiché, Ixcán' },
  { codigo: '1421', nombreCompleto: 'Quiché, Pachalum' },
  { codigo: '1422', nombreCompleto: 'Quiché, Playa Grande' },

  // Baja Verapaz
  { codigo: '1501', nombreCompleto: 'Baja Verapaz, Salamá' },
  { codigo: '1502', nombreCompleto: 'Baja Verapaz, San Miguel Chicaj' },
  { codigo: '1503', nombreCompleto: 'Baja Verapaz, Rabinal' },
  { codigo: '1504', nombreCompleto: 'Baja Verapaz, Cubulco' },
  { codigo: '1505', nombreCompleto: 'Baja Verapaz, Granados' },
  { codigo: '1506', nombreCompleto: 'Baja Verapaz, Santa Cruz El Chol' },
  { codigo: '1507', nombreCompleto: 'Baja Verapaz, San Jerónimo' },
  { codigo: '1508', nombreCompleto: 'Baja Verapaz, Purulhá' },

  // Alta Verapaz
  { codigo: '1601', nombreCompleto: 'Alta Verapaz, Cobán' },
  { codigo: '1602', nombreCompleto: 'Alta Verapaz, Santa Cruz Verapaz' },
  { codigo: '1603', nombreCompleto: 'Alta Verapaz, San Cristóbal Verapaz' },
  { codigo: '1604', nombreCompleto: 'Alta Verapaz, Tactic' },
  { codigo: '1605', nombreCompleto: 'Alta Verapaz, Tamahú' },
  { codigo: '1606', nombreCompleto: 'Alta Verapaz, San Miguel Tucurú' },
  { codigo: '1607', nombreCompleto: 'Alta Verapaz, Panzós' },
  { codigo: '1608', nombreCompleto: 'Alta Verapaz, Senahú' },
  { codigo: '1609', nombreCompleto: 'Alta Verapaz, San Pedro Carchá' },
  { codigo: '1610', nombreCompleto: 'Alta Verapaz, San Juan Chamelco' },
  { codigo: '1611', nombreCompleto: 'Alta Verapaz, Lanquín' },
  { codigo: '1612', nombreCompleto: 'Alta Verapaz, Santa María Cahabón' },
  { codigo: '1613', nombreCompleto: 'Alta Verapaz, Chisec' },
  { codigo: '1614', nombreCompleto: 'Alta Verapaz, Chahal' },
  { codigo: '1615', nombreCompleto: 'Alta Verapaz, Fray Bartolomé de las Casas' },
  { codigo: '1616', nombreCompleto: 'Alta Verapaz, La Tinta' },
  { codigo: '1617', nombreCompleto: 'Alta Verapaz, Raxruhá' },

  // Petén
  { codigo: '1701', nombreCompleto: 'Petén, Flores' },
  { codigo: '1702', nombreCompleto: 'Petén, San José' },
  { codigo: '1703', nombreCompleto: 'Petén, San Benito' },
  { codigo: '1704', nombreCompleto: 'Petén, San Andrés' },
  { codigo: '1705', nombreCompleto: 'Petén, La Libertad' },
  { codigo: '1706', nombreCompleto: 'Petén, San Francisco' },
  { codigo: '1707', nombreCompleto: 'Petén, Santa Ana' },
  { codigo: '1708', nombreCompleto: 'Petén, Dolores' },
  { codigo: '1709', nombreCompleto: 'Petén, San Luis' },
  { codigo: '1710', nombreCompleto: 'Petén, Sayaxché' },
  { codigo: '1711', nombreCompleto: 'Petén, Melchor de Mencos' },
  { codigo: '1712', nombreCompleto: 'Petén, Poptún' },

  // Izabal
  { codigo: '1801', nombreCompleto: 'Izabal, Puerto Barrios' },
  { codigo: '1802', nombreCompleto: 'Izabal, Livingston' },
  { codigo: '1803', nombreCompleto: 'Izabal, El Estor' },
  { codigo: '1804', nombreCompleto: 'Izabal, Morales' },
  { codigo: '1805', nombreCompleto: 'Izabal, Los Amates' },

  // Zacapa
  { codigo: '1901', nombreCompleto: 'Zacapa, Zacapa' },
  { codigo: '1902', nombreCompleto: 'Zacapa, Estanzuela' },
  { codigo: '1903', nombreCompleto: 'Zacapa, Río Hondo' },
  { codigo: '1904', nombreCompleto: 'Zacapa, Gualán' },
  { codigo: '1905', nombreCompleto: 'Zacapa, Teculután' },
  { codigo: '1906', nombreCompleto: 'Zacapa, Usumatlán' },
  { codigo: '1907', nombreCompleto: 'Zacapa, Cabañas' },
  { codigo: '1908', nombreCompleto: 'Zacapa, San Diego' },
  { codigo: '1909', nombreCompleto: 'Zacapa, La Unión' },
  { codigo: '1910', nombreCompleto: 'Zacapa, Huité' },

  // Chiquimula
  { codigo: '2001', nombreCompleto: 'Chiquimula, Chiquimula' },
  { codigo: '2002', nombreCompleto: 'Chiquimula, San José La Arada' },
  { codigo: '2003', nombreCompleto: 'Chiquimula, San Juan Ermita' },
  { codigo: '2004', nombreCompleto: 'Chiquimula, Jocotán' },
  { codigo: '2005', nombreCompleto: 'Chiquimula, Camotán' },
  { codigo: '2006', nombreCompleto: 'Chiquimula, Olopa' },
  { codigo: '2007', nombreCompleto: 'Chiquimula, Esquipulas' },
  { codigo: '2008', nombreCompleto: 'Chiquimula, Concepción Las Minas' },
  { codigo: '2009', nombreCompleto: 'Chiquimula, Quezaltepeque' },
  { codigo: '2010', nombreCompleto: 'Chiquimula, San Jacinto' },
  { codigo: '2011', nombreCompleto: 'Chiquimula, Ipala' },

  // Jalapa
  { codigo: '2101', nombreCompleto: 'Jalapa, Jalapa' },
  { codigo: '2102', nombreCompleto: 'Jalapa, San Pedro Pinula' },
  { codigo: '2103', nombreCompleto: 'Jalapa, San Luis Jilotepeque' },
  { codigo: '2104', nombreCompleto: 'Jalapa, San Manuel Chaparrón' },
  { codigo: '2105', nombreCompleto: 'Jalapa, San Carlos Alzatate' },
  { codigo: '2106', nombreCompleto: 'Jalapa, Monjas' },
  { codigo: '2107', nombreCompleto: 'Jalapa, Mataquescuintla' },

  // Jutiapa
  { codigo: '2201', nombreCompleto: 'Jutiapa, Jutiapa' },
  { codigo: '2202', nombreCompleto: 'Jutiapa, El Progreso' },
  { codigo: '2203', nombreCompleto: 'Jutiapa, Santa Catarina Mita' },
  { codigo: '2204', nombreCompleto: 'Jutiapa, Agua Blanca' },
  { codigo: '2205', nombreCompleto: 'Jutiapa, Asunción Mita' },
  { codigo: '2206', nombreCompleto: 'Jutiapa, Yupiltepeque' },
  { codigo: '2207', nombreCompleto: 'Jutiapa, Atescatempa' },
  { codigo: '2208', nombreCompleto: 'Jutiapa, Jerez' },
  { codigo: '2209', nombreCompleto: 'Jutiapa, El Adelanto' },
  { codigo: '2210', nombreCompleto: 'Jutiapa, Zapotitlán' },
  { codigo: '2211', nombreCompleto: 'Jutiapa, Comapa' },
  { codigo: '2212', nombreCompleto: 'Jutiapa, Jalpatagua' },
  { codigo: '2213', nombreCompleto: 'Jutiapa, Conguaco' },
  { codigo: '2214', nombreCompleto: 'Jutiapa, Moyuta' },
  { codigo: '2215', nombreCompleto: 'Jutiapa, Pasaco' },
  { codigo: '2216', nombreCompleto: 'Jutiapa, San José Acatempa' },
  { codigo: '2217', nombreCompleto: 'Jutiapa, Quesada' },



];
